version: '2'

services:

  nodeexporter:
    image: prom/node-exporter
    container_name: nodeexporter
    restart: unless-stopped
    ports:
      - 9100:9100
    network_mode: host
    labels:
      org.label-schema.group: "monitoring"

  cadvisor:
    image: google/cadvisor:v0.24.1
    container_name: cadvisor
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /cgroup/:/cgroup/:ro
    restart: unless-stopped
    ports:
      - 9010:9010
    network_mode: host
    labels:
      org.label-schema.group: "monitoring"
  

