global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "targets.rules"
  - "host.rules"
  - "containers.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    ec2_sd_configs:
      - region: ap-southeast-1
        port: 9100
    relabel_configs:
        # Only monitor instances which have a tag called Monitoring "Monitoring"
      - source_labels: [__meta_ec2_tag_Monitoring]
        regex: On
        action: keep

  - job_name: 'cadvisor'
    scrape_interval: 5s
    ec2_sd_configs:
      - region: ap-southeast-1
        port: 9010
    relabel_configs:
        # Only monitor instances which have a tag called Monitoring "Monitoring"
      - source_labels: [__meta_ec2_tag_Monitoring]
        regex: On
        action: keep

